package com.diy.labs.model.common;

import org.jsonschema2pojo.AbstractAnnotator;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.JsonNode;
import com.sun.codemodel.JDefinedClass;
import lombok.Builder;
import lombok.Data;

/** 
 * @author nicholaschin
 *
 * This class serves to help us when trying to generate json schema into POJOs. 
 * It uses Lombok and Jackson annotations to assign values when POJO are generated by jsonschema2pojo. 
 */

public class DIYLABLombokAnnotator extends AbstractAnnotator {
	
	@Override
	public void propertyOrder(JDefinedClass clazz, JsonNode propertiesNode) {
		clazz.annotate(Data.class);
		clazz.annotate(Builder.class);
		clazz.annotate(JsonIgnoreProperties.class).param("ignoreUnknown", true);
	}
}
